refactor: adding clean step and validation build ipa file

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -21,6 +21,22 @@ pipelines:
               fi
 
             - |
+              echo "Cleaning up previous builds"
+              if [ -d "./build" ]; then
+                rm -rf ./build
+                echo "Found './build' directory and deleted it."
+              else
+                echo "'./build' directory does not exist. Nothing to delete."
+              fi
+
+              if [ -d "./AppAmbitTestingApp.xcarchive" ]; then
+                rm -rf ./AppAmbitTestingApp.xcarchive
+                echo "Found './AppAmbitTestingApp.xcarchive' and deleted it."
+              else
+                echo "'./AppAmbitTestingApp.xcarchive' does not exist. Nothing to delete."
+              fi
+
+            - |
               echo "Configuring Xcode"
               sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
               export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
@@ -99,7 +115,7 @@ pipelines:
             - |
               echo "Building the IPA file"
               xcodebuild -scheme $SCHEME \
-                -archivePath ./AppAmbitTestingApp.xcarchive \
+                -archivePath ./$ARCHIVE_PATH \
                 -sdk $SDK \
                 -configuration $CONFIGURATION \
                 -destination $DESTINATION \
@@ -113,6 +129,16 @@ pipelines:
 
             - |
               echo "Packaging artifacts"
+
+              IPA_PATH=$(find build -type f -name "*.ipa" | head -n 1)
+              if [ -f "$IPA_PATH" ]; then
+                echo "IPA file found: $IPA_PATH"
+              else
+                echo "IPA file not found in build directory."
+                echo "##vso[task.logissue type=error]IPA file not found. Canceling pipeline."
+                exit 1
+              fi
+
               mkdir -p artifacts
               IPA_NAME="${APP_NAME_BASE}_${TYPE_RELEASE}.ipa"
               cp build/*.ipa "artifacts/$IPA_NAME"
